apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-s3-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-s3
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70